travis:
  secure:
    BINSTAR_TOKEN: RVn9/v+5LuQ2fiOTNlXm3MalJIeAsjRP8HgozL/Cr4rjdbGTuuWQ3k8OzA9XNygHaRQadyDioAKTT885wbGiTGrZ6nd37tytXWOjPEsFugWjD54/4UXBZVGhQ6DohGoKGYw4QkdkWSiHWRqYW0JNTSecN2cdMtkT5+MAyFea4EF28gxCMDu53xdzMCW2UCzr/2syyepqKU+xqYPN6EHouFezoBlrPJaEPlxFRPwrx03NMP+eg/fLKwdCeYn1r4NDVseg0goCOk2ubtBTB14JuTR7GeQeWeJVg2xTJq3mXa7pTkMqr2TU0GCDA0TTG9xLv9MUyF4mrJFO9lTRK9Ca5Em1SD1w2/36EnHHv+DzJYT7Ofi7tFz/3sT0KfWIWhtG5WGForCxQqIGxmJ7eafKMSvYb4plEWfgbh/hP6S04e7Yuax5jJ6hnBNqf+eQao+m30AfGnLiM5Dr2V24pV49gFYX5Vq/UwO9frsNHwuRDhLXiU+sFiGsevcRyp2eT9wo2mfNLGYVEohRTyQhpMKmQyGIARJx2FzXi8XKie5cF2Rxdrjpnq0uqLMTO6yjKTMF0bjjHdj1HoZZ+WConKSNH0trzMqnMgHdMtTWWWCvF2rDE6vo3I7/Wewrc8RvSusrXZtPNQAI+kbQ085/ApuSL7GvNmwKWjMgO5ckzV0mcQA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
