travis:
  secure:
    BINSTAR_TOKEN: DOGlJKam7ujb5FWTte2bNe4FT+crduqek75WGoHgOAGZWAjJ8QprZxcNyb86NaZ1HjsDqwUFlXLygMEkK60X1dWBF6RiSzy9dSdn5gxCgfSCipmWq7XXT6Ra1Pi+32j89ivVgQOv/Ivn3/Ut5eAK6EbCkgnYe3PSv+U/nJSqDH7KM1/SzQUd2JB9pVXri4gAFHa9eLpAKKtscLvxCyWfMo9ucXCazk2Sh4P/ZnADNlxL6zHJ8FtTzIec5rcQWYnw1w3BAtlDwxPwRuVZ6SGjDHnYvPUXeKjdTj8ddQnsA2Wpj1+VGQDU5dUUMq6iwmi1V4f8TUyL2YUqx3abY4HOMb2HjVmwI05/lYNok0STe7M5bCzDHPvmv5mftA16oIBDGOjGCxtQiwysLCc3U+QfjAAd8HkQCDnltEedrkQTdZzo2/L26i4R6tJhZ5Amr7UMHI022tMMi7YaANGPvrYrhWbgKxeCvaBuAa2eo8hSvqzmEgBMH6UJoYY7DzArblv4Q/g69uUf/w7UmBdiKegEwEYx4h4JksvG2cuIeA3jk5qawq/v3LHSsN3hz09mkxpVK48WFEzmTqzPNkk2sdcNfZbgykBbS8qVQc/woyxj02NaRnlFBQTOSYD08gpsdynvs5bCUtz7IvWcDWn8xMut1CAtVkBOv4Ygm/QCeltuznY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
