travis:
  secure:
    BINSTAR_TOKEN: j84B9DyWcVVcOkM5ww7Iy1jn0Cyuh1KDxFTcoOy6migylC6AvuO2gQcEUogjFc29BCapB4v7nnV4WZyvlf2xykLpibzU6i2PJi1nR2mjXpE02uzv1vUkkrKOCyyPjwp3G3fPZjQZiWcn71LJphm9/Qof04VQOPJ0y+5E4ekFGVTRJaL7BZzZELIq/Kyqz1e17hYQYgO32ADEcekWsFxXD+abHFCjAHk9H4IBulSsWGlDXXKocPb9FwJUskYQ9hdILCw+kXFWCm9Pk26LCUftX9SSCwPf5KlmaFRznqtoEFDXfUuwTcgScz+evrdAW43s4g97QxPNaamezlYphSqUjBUQ8Oitr7E67TXcHjEYO1uP3hkyBiPzvvTuNMQ1Hx1qrD8UqJw3RLz42GCnrYITDKsyjf/dNoIf49BEQ+97yXjsegvTLKKItPRNfmsY6mfGN2leyrxNh3uD5rAxVoFJlMcks19c0vbKWlhgsMO4WDd507OJ3E/hpPaESmDxNPaWd81u+TWPET6OD2d4WOIuY+CFjVwPU33xM0WZaUJa0u51ofxBcIfeU3zdfLnh9EETcG69D2jP/cm5uDrXFTfwiKeRpU/7aW2Gt8S4Usu1Bbe2vmLOwoEWABj8RoPHR9TD95DGuEcd0IDea/7uX5g8IkIBtkZsxfwiblJrnLbxaZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
